services:
  php:
    build: .
    container_name: fleet-php-1
    volumes:
      - ./src:/var/www/html
    depends_on:
      - sqlserver

  nginx:
    image: nginx:latest
    container_name: fleet-nginx-1
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "QJMuwa301100"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

